train_set_file: 
  question_answering: "data/hellaswag/Llama-2-7b-hf/train.parquet"
val_set_file: 
  question_answering: "data/hellaswag/Llama-2-7b-hf/validation.parquet"
test_set_file: 
  question_answering: "data/hellaswag/Llama-2-7b-hf/test.parquet"