train_set_file: 
  question_answering: "data/hellaswag/falcon-7b/train.parquet"
val_set_file: 
  question_answering: "data/hellaswag/falcon-7b/validation.parquet"
test_set_file: 
  question_answering: "data/hellaswag/falcon-7b/test.parquet"