train_set_file: 
  gsm: "data/math_qa/RedPajama-INCITE-7B-Base/train.parquet"
val_set_file: 
  gsm: "data/math_qa/RedPajama-INCITE-7B-Base/validation.parquet"
test_set_file: 
  gsm: "data/math_qa/RedPajama-INCITE-7B-Base/test.parquet"